name: Update Repository if Data Changed

on:
  schedule:
    - cron: '/15 * * * *' # 매시간마다 실행

jobs:
  check-data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

#     - name: Generate data and compare with the stored data
#       run: |
#         # 데이터 생성 스크립트 실행
#         node generate-data.js

#         # 새로 생성된 데이터 불러오기
#         NEW_DATA=$(cat static/data/now.json)

#         # 저장된 데이터 불러오기
#         STORED_DATA=$(cat static/data/data.json)

#         # 새로 생성된 데이터와 저장된 데이터 비교
#         if [ "$NEW_DATA" != "$STORED_DATA" ]; then
#           echo "Data has changed. Updating the repository..."
#           cp static/data/now.json static/data/data.json

#           # 변경 사항 커밋 및 푸시
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           git add static/data/data.json
#           git commit -m "Update data.json with new data"
#           git push
#         else
#           echo "Data is the same. No changes."
#         fi
